### PR TITLE
Brief meta type

### PR DESCRIPTION
**Pull request by azaroth42**
Per discussion in https://github.com/linked-art/linked.art/issues/296, it is more consistent to have brief-text as a metatype for the statement types, rather than as a sibling.

This change puts that in effect.

### CODE REVIEW

**Comment by kasei** [comment]
Any related tests?

**Comment by azaroth42** [comment]
No existing ones change (or ... everything passes still).  There probably should be a test that started failing ... will at least add one for metatyping generally, good call.

**Comment by kasei** [comment]
Ah. I figured some would be affected by this. New tests would be good, but otherwise this looks good.

**Comment by azaroth42** [comment]
There is a test for metatypes already: https://github.com/thegetty/crom/blob/master/tests/test_vocab.py#L26

But clearly not one for adding brief text.

**Pull request merged**
