### PR TITLE
New vocab entries, default boundary check, allow participant

### PR DESCRIPTION
**Pull request by azaroth42**

### CODE REVIEW

**Comment by kasei** [comment]
@azaroth42 AAT 300008389 is now being used for both a `city` instance, and a `CityName` class. Is that intentional? Similarly for `nation`/`CountryName` (300128207).

**Comment by azaroth42** [comment]
It is intentional. If it causes problems we can change it though :)

**Comment by kasei** [comment]
Would this be an appropriate modeling using both of those vocab elements?

```
{
  "id": "urn:uuid:b80463e2-b295-4a33-b95f-c1c9835fac70",
  "type": "Place",
  "_label": "Ghent, Belgium",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300008389",
      "type": "Type",
      "_label": "City"
    }
  ],
  "identified_by": [
    {
      "id": "urn:uuid:aa10b83f-4856-4a72-bc65-e2f1e611276d",
      "type": "Name",
      "content": "Ghent",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300008389",
          "type": "Type",
          "_label": "City"
        }
      ]
    }
  ]
}
```

**Comment by azaroth42** [comment]
I don't think you would need to classify the name like that, as it's clearly the name of a city ... but I don't think it would be wrong per se, just unnecessary.

The intent is for distinguishing city names in addresses, when the different parts of the address are broken up. e.g. street number, street name, city, state, postal code, country.

**Comment by kasei** [comment]
So keep the classification on the `Place`, and then just use `model.Name`?

**Comment by azaroth42** [comment]
Yep :)

**Pull request merged**
