### PR TITLE
Add vocab.SalePriceStatement for text about selling price

### PR DESCRIPTION
**Pull request by kasei**
What do you think about this for including information about multiple price data in German sales?

### CODE REVIEW

**Comment by azaroth42** [comment]
We have other types of actual prices that use similar terms to that. I would be worried that people use it in both places inadvertently and get things confused.

It might not be an actual acquisition, just a bid ... so probably not `vocab.AcquisitionStatement`.  It's not a Valuation of something, just a statement about the price.

I think we should ask Patricia for a sibling for the other statement types, but we can use that for now.

**Comment by kasei** [comment]
Good point about it not always being a sale. Thoughts on a better name for a statement that might be about a sale *or* a bid?

**Comment by kasei** [comment]
A complication for turning MonetaryAmounts into LinguisticObject Statements: there can be bibliographic statements and notes attached to the original monetary amount object. Those don't seem like they could be attached directly to they payment as they are specific to the price/currency.

**Comment by kasei** [comment]
@azaroth42 how about just `PriceStatement`?

**Comment by azaroth42** [comment]
`PriceStatement` with http://vocab.getty.edu/page/aat/300055694 as the classification?

**Pull request merged**
